### ISSUE TITLE
There will be an error loading your pre training weights

### ISSUE THREAD

**Issue by Yanfei-Qin** [kahnchana/svt#1]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/72698923/159133165-9c51b591-c92e-4ca2-9819-297224ea35d1.png">

**Comment by kahnchana** [comment]
Thank you for pointing this out. We have fixed this issue in the code.

**Comment by qjyyyy** [comment]
Hello, this problem still exists, because I also encountered it today.
![5f2129ba74dbccd400f0cf29c919f5e](https://user-images.githubusercontent.com/57708696/167598917-4b7d6f05-d078-40f1-9e76-9782752b096e.png)

**Comment by qjyyyy** [comment]
> Hello, this problem still exists, because I also encountered it today. ![5f2129ba74dbccd400f0cf29c919f5e](https://user-images.githubusercontent.com/57708696/167598917-4b7d6f05-d078-40f1-9e76-9782752b096e.png)

I tried to use the modified eval_knn.py and it worked, but eval_linear.py didn't work, and I couldn't solve this problem with my ability.

**Comment by kahnchana** [comment]
Can you check now? Sorry about the error.

**Comment by qjyyyy** [comment]
Thank you for your reply, KeyError has been solved, but another problem occurred. The error message is as follows. It looks like the dimensions of the data do not correspond.

By the way, when running eval_linear.py, how are the training and validation sets of the ucf101 dataset divided?
![1652271296(1)](https://user-images.githubusercontent.com/57708696/167847314-81c682ac-eb8b-45d3-af8f-910684f8b142.png)

**Comment by kahnchana** [comment]
Sorry for the late response. For `eval_linear.sh`, at the bottom of the file, set `DATA.USE_FLOW False`. I have made this update in the repo as well. The previous version was from earlier experiments involving optical flow; sorry about the error.  


In terms of UCF101 dataset, we use [MMaction2](https://github.com/open-mmlab/mmaction2/tree/master/tools/data/ucf101) to generate and use the default train / val splits generated. The different CSV are directly read by our dataset classes.

**Comment by qjyyyy** [comment]
Hello, thans for your reply.
When I tried "sh ./scripts/eval_linear.sh"
It gave me this error,
![754fd7bc25a3663733d861c9227cfd9](https://user-images.githubusercontent.com/57708696/170230602-a0e5f319-4e22-46ca-9bcf-18f3630bdf7e.png)

I think it has something to do with the CUDA, any guesses? Thanks.

**Comment by kahnchana** [comment]
What's the PyTorch and CUDA versions you are using?

**Comment by qjyyyy** [comment]
> 

Pytorch==1.7.0, and the version of CUDA is 10.2.

**Comment by kahnchana** [comment]
Can you try running it without GPU? You need to modify `eval_linear.sh` to remove the DDP call and just use 
`python eval_linear.sh --args ...`.

**Comment by kahnchana** [comment]
I've updated `eval_linear` with these fixed. Thank you for your interest in our work and for pointing our errors.
